CREATE TABLE profile
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD profile_id BIGINT;

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_profile UNIQUE (profile_id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);