CREATE TABLE cart_product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    cart_id    BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_cart_product PRIMARY KEY (id)
);

ALTER TABLE cart_product
    ADD CONSTRAINT FK_CART_PRODUCT_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_product
    ADD CONSTRAINT FK_CART_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);