CREATE TABLE country
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    iso2 VARCHAR(2),
    CONSTRAINT pk_country PRIMARY KEY (id)
);