CREATE TABLE employee
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     SMALLINT                                NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);