CREATE TABLE file
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path      VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    mime_type VARCHAR(255)                            NOT NULL,
    hash      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_file PRIMARY KEY (id)
);